### ISSUE TITLE
Multiple "INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: localhost" errors when running Home-Assistant

### ISSUE THREAD

**Issue by nauticus25** [kk7ds/pynx584#3]
Not sure if this is actually an issue.  But when I run HA with the nx584 component installed, I get many lines per minute of

```
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: localhost
```

in the scrolling log on the RPi.  When I disable the nx584 component, the errors go away.  Is this an error, or is it the nx584 component in HA pinging the nx584 board often to stay on top of state changes?

BTW, nx584 running on a 1st gen RPi B using a FTDI USB to serial cable works great!  Thanks again for all your help getting things configured!

**Comment by kk7ds** [comment]
Yeah, those are expected. That is just overly verbose logging from a library that nx584 uses every time the client makes a request to the server. The periodic requests you see are the client long-polling for events from the server so that HA notices immediately when you open/close a door, etc.

Glad to hear it's working. Thanks for reporting the issues you did find and for your patience!

**Comment by kk7ds** [comment]
BTW, I think you can probably squelch them in the HA logging config if you don't want to see them:

https://home-assistant.io/components/logger/

**Comment by nauticus25** [comment]
Ok, it's not indicating an error, then.  Good to know.  Thanks!
